### ISSUE TITLE
Disabling OPT_CIS breaks "make" in zipcpu/rtl

### ISSUE THREAD

**Issue by DoctorWkt** [ZipCPU/zipcpu#1]
I just commented out OPT_CIS in _rtl/cpudefs.v_. When I do a "make" in rtl/, it says:

`%Warning-UNUSED: core/zipcpu.v:268: Signal is not used: dcd_Rpc
%Warning-UNUSED: Use "/* verilator lint_off UNUSED */" and lint_on around source to disable this message.
%Error: Exiting due to 1 warning(s)`

Cheers, Warren

**Comment by ZipCPU** [comment]
Sorry ... didn't notice these had been accumulating!  I just fixed this in the dev/ branch.  You'll still have problems with the toolsuite, though.  The assembler needs to be given a "--nocis" option in order to build software without the CIS instruction set.  This includes while building the C-library, and the GCC library.
