### ISSUE TITLE
Building the tool chain failed

### ISSUE THREAD

**Issue by sakshamg96** [ZipCPU/zipcpu#16]
I followed all the steps from http://zipcpu.com/zipcpu/2018/01/31/cpu-build.html
I am getting some warnings and errors when I do `make` inside zipcpu directory. See attached file.
[make issue.txt](https://github.com/ZipCPU/zipcpu/files/6872537/make.issue.txt)

**Comment by ZipCPU** [comment]
**The issue**: Verilator updated its unused variable checking to include parameters, not just registers.

This has been fixed in the zipcore branch.  However, the ZipCore branch has yet to be merged into the mainline.  It has had a major upgrade to the debug port which hasn't yet been documented.  Once merged, this will be fixed.

Dan

**Comment by ZipCPU** [comment]
Also ... I'm leaving this open because it is a legitimate bug that needs fixing, and shouldn't be left open that long.

**Comment by ZipCPU** [comment]
Please try again with the latest release.  That should fix these bugs.  It will also update GCC to version 10.3, since I can't build 6.2 on my computer any more.

Dan
